apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swapp-registration-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: swapp
    app.kubernetes.io/component: registration-service
spec:
  project: swapp
  source:
    repoURL: https://github.com/fambelic/swApp.git
    targetRevision: iac
    path: registration-service
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
