apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swapp-root
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: swapp
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: teacher-4
  source:
    repoURL: https://github.com/fambelic/swApp.git
    targetRevision: HEAD
    path: microservices
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
