---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: swapp-swapp-gateway
  namespace: teacher-3
spec:
  encryptedData:
    jwtSecret: AgCcEAHLgCdWWdG+y6eatoQ5gmloyoDYu3TP7WwKVyf8qubly3nCef/on9Hb9xR/+hawk/+k3Z6jRqUtbjHRfBC0GOwZaqr2WMkpDDO7iLoA9ByrSif5Xqc8E3Se78ldjuz06oilZgc7yPiddyjHiQ6wBFwD5gez3pi3Kqf4prPsy0CQK0s++7qYotJTvPxHa30bQ6TPGZziP5YdKmWQIKiPiXQIdl0eK4Kl84P3y5CAXcnEXEd9CMNfjspfW94ksIe5RACxuaFd6Ge8IsTzea1yq7NG70xr0kEERvKbfQqUw79P0V4RIcuOopnxmrT5uIss1+DSt2I37yqJIJ8edSbBTRnhzw/dI2CH/mMnbZZi+jMXVviM0rDzAAIoiW4+0P9Vwodv+PGTEmav7HbCwRB+NxBIZFLs1/5mGGMtr9DZlHWLAHuUDWdmCZbKy5NzEpa8GzqpucNsWqciwe07cHMh9pBfUdNPwLJtBtiSQvYLcUiHWCuCQUumClW+bJHpPDwkKAMbhmvj2DzGD+NGQStpT+gleWIpqjyVpm+nKJSf12UiUj0hwUgRlBTxY43sLBW7wz/foGrYeyQZfR9RoYThdMmNphorIgyVHz2cvrV7jEiJq8Lp0neUrgW0H85cNeztjcCH9slEAvNSxgwgYCY3cCfKqMB6WMnlHUlbbHOpTYJSq+dw8pxLVnzFMlU+de2ujmqT+DAZqeI=
  template:
    metadata:
      name: swapp-swapp-gateway
      namespace: teacher-3
