apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "db-service.fullname" .) .Values.auth.secretName }}
  labels:
    {{- include "db-service.labels" . | nindent 4 }}
stringData:
  user: {{ .Values.auth.username | quote }}
  password: {{ .Values.auth.password | quote }}
  db: {{ .Values.auth.database | quote }}
