apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "db-service.fullname" . }}
  labels:
    {{- include "db-service.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "db-service.headlessServiceName" . }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "db-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "db-service.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "db-service.componentAppName" (dict "root" . "component" (default "db" .Values.componentName)) }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "db-service.fullname" .) .Values.auth.secretName }}
                  key: db
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "db-service.fullname" .) .Values.auth.secretName }}
                  key: user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ default (include "db-service.fullname" .) .Values.auth.secretName }}
                  key: password
          volumeMounts:
            - name: mongodata
              mountPath: /data/db
            - name: mongodata
              mountPath: /data/configdb
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
  volumeClaimTemplates:
    - metadata:
        name: mongodata
      spec:
        accessModes:
          {{- toYaml .Values.persistence.accessModes | nindent 10 }}
        {{- if .Values.persistence.storageClassName }}
        storageClassName: {{ .Values.persistence.storageClassName }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
