apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ads-service.fullname" . }}
  labels:
    {{- include "ads-service.labels" . | nindent 4 }}
data:
  mongoHost: {{ default (include "ads-service.peerFullname" (dict "root" . "component" .Values.dependencies.dbComponentName)) .Values.config.mongoHost | quote }}
  rabbitHost: {{ default (include "ads-service.peerFullname" (dict "root" . "component" .Values.dependencies.rabbitComponentName)) .Values.config.rabbitHost | quote }}
