apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapp-swapp-matcher
spec:
  template:
    spec:
      containers:
        - name: swapp-matcher
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
