spring:
  main:
    allow-circular-references: true
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: demodb
      password: example
      port: 27017
      host: 127.0.0.1
  application:
    name: apigateway
server:
  port: 8087

zuul:
  routes:
    registration:
      path: /registration/**
      url: http://localhost:8082/
    announce:
      path: /ads/**
    mockoon:
      path: /annunci/ad/**
      url: http://127.0.0.1:3000/

private.security.jwt.secret: otherpeopledontknowit