spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      database: demodb
      password: example
      port: 27017
      host: 127.0.0.1
  application:
    name: authservice
server:
  port: 8087


private.security.jwt.secret: otherpeopledontknowit