apiVersion: v1
kind: Secret
metadata:
  name: {{ default (include "apigateway-service.fullname" .) .Values.gatewaySecret.name }}
  labels:
    {{- include "apigateway-service.labels" . | nindent 4 }}
stringData:
  {{ .Values.gatewaySecret.jwtSecretKey }}: {{ .Values.gatewaySecret.jwtSecretValue | quote }}
