---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: swapp-swapp-gateway
  namespace: teacher-3
spec:
  encryptedData:
    jwtSecret: AgBiPSGGs5y90xRgsBsruHKxFAOM4rqf3EjxESeDJCnW+KqK/cChUHHO3/Kz2KXVSM0XxaDdWzrp9/QkKYznLw3N/kxAfrngVaa9FENk9pZxr5avNBZE4wkkBDoG5fRo+FnH5hAxqdwOllHsVLrkaC4BtzHM84N0wVVWOIzJj0rMIJcnlZuurgXdjo4AjHvEbNsAaoVJy29lAhsi+XQCgbuZEEbnOTbTwg9ajk0+POodMC2oe/s7/eY5bJ8of4so1OEA0o+AFb+nZDA8Cu+GYV/6k3bAc5nI3OfyeG7BJuxIJc+//tyNx2yR0Qh3FolAKEhlBUWTdq8nlENZPpIJLJx/0DdgSdLOz8c5qRa/IkbLEz61cNgcAy/Yjs9KyB/OjPWQQnnY4wWH4i9URXX2jkwmvejAjsmSQ96jCS5ju5aNmzxzfTmJeLEXeF3/OK7gm8gqgswe4krrn25etoylhDbZzSa6V5JixBBcDVlGy3zSFBJI2oOPdCd/MTy9bDJyJrznYqpXryvo4w5XLaR2mZ/giRSm584jflaqJJdRgyW6kir2NyOS1IbDzhW9u3KpEA+XhROYcVzhugY0SZLZwmT3CBcclrO4sXjLTYFG5EhA9BCz5QQeuFIBUX3yxEpMxS6GX/4vnzfA1Mrkgb5tCshVs7pBjjBUQaxAyyLbZOUx5VhSqQRkxMdYVdZYEvMr5bxItzLe8cqqHuQ=
    template:
    metadata:
      name: swapp-swapp-gateway
      namespace: teacher-3
