---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: swapp-swapp-gateway
  namespace: argocd
spec:
  encryptedData:
    jwtSecret: AgAbVk116L0OKaWaAL/YR694da/iJQG5Mealpchh6x9mfsy2wR7uCKAtTvVI2ENG3rPPF4l+d78EkMkeYUYiZhvR0z4TKvz6MA4c0QPtONviZSbUrSPlEAVQ783yfMEJv5y77ejuC4BQx/H7mxrVn2KyFglW9BR1mXgNfd66bJlU4d2TZIP/iMN/PxVU34KKw6GcAqLELlGrQfqNsLn1oOgZyexHg85lIqjVygaBCMhr9ODaAL2b6GQ2ZmdYFqciGlfjdbpsCGtO4HKThxZMcxxj5AGPSqhMbA/E6T+htzkvdtiO/J7X1L0vARUoAHBp/4cDrglgHki3qQVKI6bWUumQyoNztoj5RF2P+VBc8en3I8+btLhlTYDpI3XEqiOyPNXL9BgkZ9HZmL3yD8gyf3kO3bqYxxwM8AXTVgKS/TlXqA0hy3F0XLfF5RAIidmaVFIALok6xk3AvlbcDt6CuImpG22MNvQZloiX1nuFc7rWGpXL/vu7Df64i0Y7n1kKzIq85F7lcHrXqoSSmDbn/oc2cRNDyCNaajHFG1P2XzpCMsc9fIXbCN4FbBRssV+rU2djHwNpv1U1hQTWsyN6Njk+WTzMW/NGEWt9z5z2wNw+RIRrdyWbWuX45nZNvHCWVVktEprkzP+sHW3/YPtGPdp9KMsspT+utoKlBNu/QLCWRkY4xw5ZTF0lMnhLLAYxpOvsqovMTIAfjow=
  template:
    metadata:
      name: swapp-swapp-gateway
      namespace: argocd
