---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: swapp-swapp-gateway
  namespace: teacher-3
spec:
  encryptedData:
    jwtSecret: AgAE6c6r8UJk8uhzd73TPxZ6KBpQ3SWQi/fqPOicCP+K7th15K4G3kzFNMgbKOJGsGpo2N3j0o+3o6/lh80Oi1GvL/aJ/FZVz2HXPfI0QvGVcaMfmv08BbR/2InphJ4CsafGoWFnv5bHKwsTjwZnz6dSl2Qp/tr7qhZQwlAqd5rjxzqjsvnh+aoaLvj2AZpL+JFgMNj/obK4Q0+TC4isO7E+M06ucu0NtCXWgOaoD99dQsUcr/C4yBE1PThbWpMtcHY1Ogf5zVgdXt2vRuU9USPD5lUvv7jU/r4UJ24tpJOrb8azf/eb1R3ed8aSgLYRoVSA6DviYOeENw0QZBCEN6OSxG5qhZkQNrbnUGq13xzjPWU0S1ALSu2Utsr+iSvNsWNXJbgdS0bX+5qEgmCeSZAZRzq1Bc6xTk5nBtBPDSoHjGJ2MyyVG8mxYXAqt5ZP0R6wxWh94/Las5c96Iq17kVUCelLw3JFmQbPyGn6GCoWtKE8F5iFzShrkAVa4rdFc4uXxtTT8MAi6G87DjzqphawJO/OUQQROuF+VaMBtoUUHPOjJ2yFatDkHB1LWNxbJEyNzFDIHcqmrUa584pt1BBaNaeuKXNopQgUME/2UVn1RgiGCY0hpR9/mW8ZRt9pY0Y5IwL4a0nnxoYM6HDTyKLACtlAXMs2ur0775opDoYr2rfPIDuVRm6oxRwiq5LEm6AnL0MkVq0ZpqQ=
  template:
    metadata:
      name: swapp-swapp-gateway
      namespace: teacher-3
