---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: swapp-swapp-gateway
  namespace: teacher-3
spec:
  encryptedData:
    jwtSecret: AgBNf/VkTqBbC1nfCv25EbKD1DjTQFimoxjNV+SmY4MP4M8PqzvjixkdQ6sCfxPspDB8YDVI9Ypm5eXlPUhNOuv7wtVO3lHertkkhpFga/f7x5GjCuYO/rTpP2wWtPOodYLevncCiJUb6WrFax0sa0iMMP4XgZR6IKhs6g/wl5hyQQ2eV8SnJfkG2Jy1aOYKpxZvt3FPxzIN3Sj9rpMYgnmdWbXztE55jPap1H6E/rX/bjAmsZx4GS75p/x3Faz1EDgpYuNbmnbnQ4dQ5y7CnFdpdiugmhoisWRZ5QS9b3hPnfGJkwLH13O3VzjED9+RloLhCLatFAOuQLPuirKRwLDCRx4Vgz8EAuXWIrY97tiYY385b1MeAFWfSfnLyVYEq46x4cQ9bUf2F0m7vyVcbNFI6Y3KV2x1kggmnPmA8vIxQQXddDUpl/MeULz54dWI1whuDrGgXzMuGrJhIJ81R+57iBb6Ugs4J+Q0ujSN5JM5dqYuco7H0RblYQITKJZ79urUdg0ZnM609pEajTN9pgGp/4DKibYw8khbUDh/+ceRRNlJ5Ld5/lnIGAEjA3eU4xLtHkJ8eW/zBx3jBuMpKSNGHtWgxlj9rwgqANkj0boAAl29PHXSTtlIOsrUZ6K5iJBv8q1xkA/j1uyzJdkawMLmmah88xQfPNDk162qhaRF/1F84aLj7gBwJ3jE6nNTeRcNuYO87bw8/I0=
  template:
    metadata:
      name: swapp-swapp-gateway
      namespace: teacher-3
