apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: swapp-swapp-db
spec:
  template:
    spec:
      containers:
        - name: swapp-db
          resources:
            requests:
              cpu: "500m"
              memory: "1Gi"
            limits:
              cpu: "2000m"
              memory: "2Gi"
