apiVersion: apps/v1
kind: Deployment
metadata:
  name: swapp-swapp-matcher
spec:
  template:
    spec:
      containers:
        - name: swapp-matcher
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1000m"
              memory: "1Gi"
