apiVersion: v1
kind: Service
metadata:
  name: {{ include "registration-service.fullname" . }}
  labels:
    {{- include "registration-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: http
  selector:
    {{- include "registration-service.selectorLabels" . | nindent 4 }}
