# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build

on:
  push:
    branches: [ "svil" ]
  pull_request:
    branches: [ "svil" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        component:
        - adservice
        - apigateway
        - matcher_service
        - registration_service
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean install --file ./${{ matrix.component }}/pom.xml -Dmaven.test.skip=true
    - name: build image
      run: docker build ./${{ matrix.component }} -f ./${{ matrix.component }}/Dockerfile -t mascorra/swapp-${{ matrix.component }}:latest
    - name: login and push Docker image
      run: docker login -u=camix777 -p=9auAHI5s%@41s@%aK$I5 && docker push mascorra/swapp-${{ matrix.component }}:latest
      
    
      

